"""Permutation groups for the word problems: S_g, A_g and the Mathieu group M11.

Conventions: an element is a tuple p with p[i] the image of point i; the running product after
letters x_1..x_t is x_t o ... o x_1; class 0 is the identity.

Quotient heads. A head spec names a quotient of the right-regular action, i.e. a function
phi(class) whose next value depends on phi and the letter only:
    ("point", i)  g states, the image of point i
    ("pairing",)  3 states, S4 acting on the three pair partitions of 4 points
    ("parity",)   2 states, S_g only
    ("coset", k)  |G| / k states, the left cosets of the cyclic group of (0 1 ... k-1)
"""

import functools
import itertools
import math

import numpy as np


# --- S_g and A_g ---------------------------------------------------------------------------------

def _parity(p) -> int:
    return sum(1 for i in range(len(p)) for j in range(i + 1, len(p)) if p[i] > p[j]) % 2


@functools.lru_cache(maxsize=None)
def permutation_elements(g: int, group: str = "S") -> tuple:
    """Elements of S_g (group "S") or A_g ("A"), identity first."""
    perms = list(itertools.permutations(range(g)))
    if group == "A":
        perms = [p for p in perms if _parity(p) == 0]
    return tuple(perms)


@functools.lru_cache(maxsize=None)
def permutation_cayley(g: int, group: str = "S") -> np.ndarray:
    """[C, C] int32: tbl[a, b] = class of (b after a)."""
    elems = permutation_elements(g, group)
    index = {p: i for i, p in enumerate(elems)}
    tbl = np.empty((len(elems), len(elems)), dtype=np.int32)
    for a, pa in enumerate(elems):
        for b, pb in enumerate(elems):
            tbl[a, b] = index[tuple(pb[pa[i]] for i in range(g))]
    return tbl


def permutation_num_classes(g: int, group: str = "S") -> int:
    return math.factorial(g) // 2 if group == "A" else math.factorial(g)


def permutation_alphabet(g: int, group: str = "S") -> tuple:
    """Adjacent transpositions (i, i+1) for S_g; adjacent 3-cycles (i, i+1, i+2) for A_g."""
    gens = []
    for i in range(g - 1 if group == "S" else g - 2):
        p = list(range(g))
        if group == "S":
            p[i], p[i + 1] = p[i + 1], p[i]
        else:
            p[i], p[i + 1], p[i + 2] = p[i + 1], p[i + 2], p[i]
        gens.append(tuple(p))
    return tuple(gens)


@functools.lru_cache(maxsize=None)
def permutation_alphabet_index(g: int, group: str = "S") -> np.ndarray:
    """[A] int32: class of each letter. Raises if the letters do not generate the group."""
    index = {p: i for i, p in enumerate(permutation_elements(g, group))}
    idx = np.asarray([index[p] for p in permutation_alphabet(g, group)], dtype=np.int32)
    tbl = permutation_cayley(g, group)
    seen, frontier = {0}, [0]
    while frontier:
        a = frontier.pop()
        for l in idx:
            b = int(tbl[a, l])
            if b not in seen:
                seen.add(b)
                frontier.append(b)
    if len(seen) != tbl.shape[0]:
        raise ValueError(f"the alphabet does not generate {group}{g}")
    return idx


def permutation_alphabet_size(g: int, group: str = "S") -> int:
    return len(permutation_alphabet(g, group))


def permutation_next_class(g: int, group: str = "S") -> np.ndarray:
    """[A, C] int32: the class letter a sends class c to."""
    return permutation_cayley(g, group)[:, permutation_alphabet_index(g, group)].T.copy()


# --- quotient heads ------------------------------------------------------------------------------

_PAIRINGS = (frozenset({frozenset({0, 1}), frozenset({2, 3})}),
             frozenset({frozenset({0, 2}), frozenset({1, 3})}),
             frozenset({frozenset({0, 3}), frozenset({1, 2})}))


def permutation_quotient_size(spec: tuple, g: int, group: str = "S") -> int:
    """States of one head spec."""
    kind = spec[0]
    if kind == "point":
        return g
    if kind == "pairing":
        return 3
    if kind == "parity":
        return 2
    if kind == "coset":
        return permutation_num_classes(g, group) // int(spec[1])
    raise ValueError(f"unknown head spec {spec!r}")


def _cyclic_subgroup(k: int, g: int) -> tuple:
    """The cyclic subgroup generated by the k-cycle (0 1 ... k-1) of S_g."""
    cyc = tuple((i + 1) % k if i < k else i for i in range(g))
    out, cur = [tuple(range(g))], cyc
    while cur != out[0]:
        out.append(cur)
        cur = tuple(cyc[cur[i]] for i in range(g))
    return tuple(out)


def _quotient_code(spec: tuple, g: int, group: str) -> np.ndarray:
    """[C] head state of every class under one head spec (unnormalised labelling)."""
    elems = permutation_elements(g, group)
    kind = spec[0]
    if kind == "point":
        return np.asarray([p[int(spec[1])] for p in elems], dtype=np.int32)
    if kind == "pairing":
        index = {pr: i for i, pr in enumerate(_PAIRINGS)}
        return np.asarray([index[frozenset(frozenset(p[q] for q in pair) for pair in _PAIRINGS[0])]
                           for p in elems], dtype=np.int32)
    if kind == "parity":
        return np.asarray([_parity(p) for p in elems], dtype=np.int32)
    if kind == "coset":
        H = _cyclic_subgroup(int(spec[1]), g)
        index = {}
        keys = [min(tuple(p[h[i]] for i in range(g)) for h in H) for p in elems]
        for k in keys:
            index.setdefault(k, len(index))
        return np.asarray([index[k] for k in keys], dtype=np.int32)
    raise ValueError(f"unknown head spec {spec!r}")


def _verified_heads(raw_codes, sizes, next_cls: np.ndarray) -> tuple:
    """Per head (code [C], table [A, n]), relabelled so the identity class is state 0.

    Raises unless every head uses all its states, steps on its own state and the letter alone
    (table[a, code[c]] = code[next_cls[a, c]]), and the family separates all classes."""
    n_letters, n_classes = next_cls.shape
    out = []
    for code, n in zip(raw_codes, sizes):
        code = np.asarray(code, dtype=np.int32)
        if code[0] != 0:
            swap = np.arange(n, dtype=np.int32)
            swap[0], swap[code[0]] = code[0], 0
            code = swap[code]
        if np.unique(code).size != n:
            raise ValueError(f"a head of size {n} uses {np.unique(code).size} states")
        table = np.full((n_letters, n), -1, dtype=np.int32)
        for a in range(n_letters):
            nxt = code[next_cls[a]]
            table[a, code] = nxt
            if np.any(table[a][code] != nxt):
                raise ValueError(f"a head of size {n} does not step on its own state")
        out.append((code, table))
    if np.unique(np.stack([c for c, _ in out], axis=1), axis=0).shape[0] != n_classes:
        raise ValueError("the head family does not separate the classes")
    return tuple(out)


@functools.lru_cache(maxsize=None)
def permutation_quotient_codes(g: int, group: str, specs: tuple) -> tuple:
    """Verified (code, table) per head spec on S_g / A_g."""
    return _verified_heads([_quotient_code(s, g, group) for s in specs],
                           [permutation_quotient_size(s, g, group) for s in specs],
                           permutation_next_class(g, group))


# --- M11 -----------------------------------------------------------------------------------------
# M11 (order 7920) acts sharply 4-transitively on 11 points, so the images of points 0..3 identify
# an element. Elements are enumerated by BFS; no Cayley table is built.

MATHIEU_GENERATORS = ((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0),
                      (0, 1, 6, 9, 5, 3, 10, 2, 8, 4, 7))      # ATLAS standard generators
MATHIEU_DEGREE = 11
MATHIEU_ORDER = 7920
MATHIEU_KEY_POINTS = (0, 1, 2, 3)


def _perm_inverse(p: tuple) -> tuple:
    q = [0] * len(p)
    for i, v in enumerate(p):
        q[v] = i
    return tuple(q)


@functools.lru_cache(maxsize=None)
def mathieu_alphabet() -> tuple:
    """The two generators and their inverses."""
    a, b = MATHIEU_GENERATORS
    return a, b, _perm_inverse(a), _perm_inverse(b)


def mathieu_alphabet_size() -> int:
    return len(mathieu_alphabet())


def mathieu_num_classes() -> int:
    return MATHIEU_ORDER


@functools.lru_cache(maxsize=None)
def mathieu_elements_array() -> np.ndarray:
    """[7920, 11] int32, identity first. Raises if the generators do not close to |M11|."""
    ident = tuple(range(MATHIEU_DEGREE))
    seen, order, frontier = {ident}, [ident], [ident]
    while frontier:
        w = frontier.pop()
        for g in mathieu_alphabet():
            c = tuple(g[j] for j in w)
            if c not in seen:
                seen.add(c)
                order.append(c)
                frontier.append(c)
    if len(order) != MATHIEU_ORDER:
        raise ValueError(f"the generators close to {len(order)} elements, not {MATHIEU_ORDER}")
    return np.asarray(order, dtype=np.int32)


@functools.lru_cache(maxsize=None)
def mathieu_alphabet_array() -> np.ndarray:
    """[4, 11] int32."""
    return np.asarray(mathieu_alphabet(), dtype=np.int32)


def _mathieu_key(images: np.ndarray) -> np.ndarray:
    """[..., 11] -> base-11 key of the images of MATHIEU_KEY_POINTS."""
    key = np.zeros(images.shape[:-1], dtype=np.int32)
    for i in MATHIEU_KEY_POINTS:
        key = key * MATHIEU_DEGREE + images[..., i]
    return key


@functools.lru_cache(maxsize=None)
def mathieu_key_table() -> np.ndarray:
    """[11^4] int32: key -> class, -1 where no element has that key."""
    keys = _mathieu_key(mathieu_elements_array())
    if np.unique(keys).size != MATHIEU_ORDER:
        raise ValueError("the key points do not separate the elements")
    table = np.full(MATHIEU_DEGREE ** len(MATHIEU_KEY_POINTS), -1, dtype=np.int32)
    table[keys] = np.arange(MATHIEU_ORDER, dtype=np.int32)
    return table


@functools.lru_cache(maxsize=None)
def mathieu_next_class() -> np.ndarray:
    """[4, 7920] int32: the class letter a sends class c to."""
    elems, table = mathieu_elements_array(), mathieu_key_table()
    nxt = np.stack([table[_mathieu_key(letter[elems])] for letter in mathieu_alphabet_array()])
    if nxt.min() < 0:
        raise ValueError("a letter leaves M11")
    return nxt.astype(np.int32)


@functools.lru_cache(maxsize=None)
def mathieu_quotient_codes(specs: tuple) -> tuple:
    """Verified (code, table) per ("point", i) head spec on M11."""
    elems = mathieu_elements_array()
    return _verified_heads([elems[:, int(s[1])] for s in specs], [MATHIEU_DEGREE] * len(specs),
                           mathieu_next_class())
